### ISSUE TITLE
This plugin doesn't work with SonarQube 7.7

### ISSUE THREAD

**Issue by AdriedB** [willemsrb/sonar-issueresolver-plugin#6]
Hi, It seems that this plugin doesn't work with SonarQube 7.7. 
Probably it should do the job for which I am looking, transferring issues from one SonarQube database to another, but then I need a working version. Who can help me?

**Comment by Bronek777** [comment]
Hi
Tool that you probabyl want is included only in comercial version of
sonarqube. If I remember the name is "db migration tool". They can move all
data from one database to another event in diferent db engine. Not single
issue.
Move one single issue is imposible.

This plugin resolves issue between projects on same database. Its works on
one instance but on old version of sonarqube. They search same issue on
diferent projects base on Path, rule etc. And set same issue status like
"false-positive". Unfortunatley This funcionality is also add in comercial
version on sonarqube in "developer edition".

Regards
Sebastian

czw., 3 paź 2019, 11:34 użytkownik AdriedB <notifications@github.com>
napisał:

**Comment by AdriedB** [comment]
Hi,

Thanks for your answer. We are using the free edition, so we are not able to move our project. I don-not want to move a single issue. I want to move all the issues of a particular project.

But for now i know that is not possible, unfortunately.

Regards,
Adrie
